// Package store salva os reviews em markdown no disco.
package store

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/beroni/bazel/internal/agent"
)

// Save grava o review em markdown e devolve o caminho do arquivo.
func Save(dir string, res agent.Result) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	name := fmt.Sprintf("%s-%d-%s.md",
		sanitize(res.PR.Repo),
		res.PR.Number,
		time.Now().Format("20060102-150405"),
	)
	path := filepath.Join(dir, name)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s#%d — %s\n\n", res.PR.Repo, res.PR.Number, res.PR.Title)
	fmt.Fprintf(&b, "- Author: @%s\n", res.PR.Author.Login)
	fmt.Fprintf(&b, "- Branch: `%s`\n", res.PR.HeadRefName)
	fmt.Fprintf(&b, "- URL: %s\n", res.PR.URL)
	fmt.Fprintf(&b, "- Diff: +%d −%d across %d file(s)\n", res.PR.Additions, res.PR.Deletions, res.PR.ChangedFiles)
	fmt.Fprintf(&b, "- Reviewed at: %s (took %s)\n", time.Now().Format("2006-01-02 15:04"), res.Duration.Round(time.Second))
	if res.Agent != "" {
		fmt.Fprintf(&b, "- Agent: %s\n", agentLine(res))
	}
	if u := res.Usage.String(); u != "" {
		fmt.Fprintf(&b, "- Spend: %s\n", u)
	}
	if res.Posts {
		b.WriteString("- ⇧ This agent published the review to the PR on its own.\n")
	}
	if res.Truncated {
		b.WriteString("- ⚠️ The diff was truncated before it reached the agent.\n")
	}
	b.WriteString("\n---\n\n")
	b.WriteString(res.Body)
	b.WriteString("\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// CommentBody monta o texto publicado no PR.
func CommentBody(res agent.Result) string {
	var b strings.Builder
	b.WriteString("## 🥚 Automated review — Bazel\n\n")
	b.WriteString(res.Body)
	b.WriteString("\n\n---\n")
	fmt.Fprintf(&b, "<sub>Generated by [Bazel](https://github.com/beroni/bazel) at %s", time.Now().Format("2006-01-02 15:04"))
	if res.Agent != "" {
		fmt.Fprintf(&b, " · %s", res.Agent)
	}
	if res.Truncated {
		b.WriteString(" · diff truncated")
	}
	b.WriteString("</sub>\n")
	return b.String()
}

// agentLine descreve quem rodou: o nome da escolha e, quando ela encadeia mais
// de um agente, o tempo de cada passo.
func agentLine(res agent.Result) string {
	if len(res.Steps) < 2 {
		return res.Agent
	}
	parts := make([]string, 0, len(res.Steps))
	for _, s := range res.Steps {
		part := fmt.Sprintf("%s (%s)", s.Name, s.Duration.Round(time.Second))
		if s.Err != nil {
			part += " ✗"
		}
		parts = append(parts, part)
	}
	return res.Agent + " — " + strings.Join(parts, " → ")
}

func sanitize(s string) string {
	return strings.NewReplacer("/", "-", " ", "-", ":", "-").Replace(s)
}

// Entry é um review já salvo em disco.
//
// Repo e Number saem do cabeçalho do arquivo e são o que permite agir sobre um
// review depois de o servidor ter sido reiniciado: sem eles, um review salvo é
// só texto — não dá para publicá-lo no PR de onde veio.
type Entry struct {
	Name    string    `json:"name"`
	Title   string    `json:"title"`
	Repo    string    `json:"repo,omitempty"`
	Number  int       `json:"number,omitempty"`
	ModTime time.Time `json:"mod_time"`
	Size    int64     `json:"size"`
}

// List devolve os reviews salvos, do mais novo para o mais velho. Diretório
// inexistente é uma lista vazia, não um erro: ninguém revisou nada ainda.
func List(dir string) ([]Entry, error) {
	items, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []Entry
	for _, it := range items {
		if it.IsDir() || !strings.HasSuffix(it.Name(), ".md") {
			continue
		}
		info, err := it.Info()
		if err != nil {
			continue
		}
		title := heading(filepath.Join(dir, it.Name()))
		repo, number := PRFromTitle(title)
		out = append(out, Entry{
			Name:    it.Name(),
			Title:   title,
			Repo:    repo,
			Number:  number,
			ModTime: info.ModTime(),
			Size:    info.Size(),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ModTime.After(out[j].ModTime) })
	return out, nil
}

// Read devolve o markdown de um review salvo. name é só o nome do arquivo —
// qualquer coisa com separador de caminho é recusada para não deixar a
// interface web ler fora do diretório de reviews.
func Read(dir, name string) (string, error) {
	if name == "" || name != filepath.Base(name) || strings.Contains(name, "..") {
		return "", fmt.Errorf("invalid review name: %q", name)
	}
	if !strings.HasSuffix(name, ".md") {
		return "", fmt.Errorf("invalid review name: %q", name)
	}
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// heading lê o título do review (a primeira linha "# ..."), sem carregar o
// arquivo inteiro.
// Heading é o título de um review já lido — a primeira linha "# ...".
func Heading(file string) string {
	for _, line := range strings.SplitN(file, "\n", 6) {
		if line = strings.TrimSpace(line); strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return ""
}

// PRFromTitle tira o PR do cabeçalho de um review salvo — o
// "acme/api-core#482 — título" que o Save escreve na primeira linha. É o que
// liga o markdown em disco de volta ao pull request.
func PRFromTitle(title string) (string, int) {
	head, _, _ := strings.Cut(title, " ")
	repo, num, ok := strings.Cut(head, "#")
	if !ok || !strings.Contains(repo, "/") {
		return "", 0
	}
	n, err := strconv.Atoi(num)
	if err != nil || n <= 0 {
		return "", 0
	}
	return repo, n
}

// ReviewBody é o relatório dentro de um review salvo, sem o cabeçalho que o
// Save escreveu — é o texto que o agente produziu, e é ele que vai ao PR.
func ReviewBody(file string) string {
	if _, corpo, ok := strings.Cut(file, "\n---\n"); ok {
		return strings.TrimSpace(Unwrap(corpo))
	}
	return strings.TrimSpace(Unwrap(file))
}

func heading(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for i := 0; sc.Scan() && i < 5; i++ {
		if line := strings.TrimSpace(sc.Text()); strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return ""
}
